#https://gist.github.com/kingspp/9451566a5555fb022215ca2b7b802f19

version: 1
formatters:
  brief:
      format: "%(levelname)s - %(message)s"
  precise:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: brief
    stream: ext://sys.stdout

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: precise
    filename: /tmp/vodes_errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
    level: INFO
    handlers: [console]
    propagate: yes

loggers:
  vodes:
    level: INFO
    handlers: [error_file_handler, console]
    propagate: no