language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: pRnGKpzeclD+sgCFUqNDpnZ2WNUURvU9cO7nSJJHGuhRMz5Wi2gwhcdKsa4Tq2MqrbinuGuht8UyOdMxo+Nbr3gPgX+WccegMZXR32UTVuWWaZfczsJ28aZIguTn/C16ze1b0ca/zaKATqWkaHg+cEDOPa9fqUMDXVZo9zyKmHhuZEozGYdEV/haeVNFxfuI+hlbnn3lVr591OpRsLhT0gxx24ItFZqDPbEGnE/R583AuT9NEjbnPMC9rfHbXqe3eeRPXZAJn3lmAi+VBeAXs5R2nR+SRoRsB+N0NXwQf+vL28+0oV5AbY37HjkH4+5ZUHs1uRPN3SBYLMO3y1H5PC7tvLQ3/M9bCCgtaCdoj472EPCypLBo8nTPTQk8FphCQhnMuCAfprxUPLZDpI+j0jSDu5jA9JPwji02BjWYg6x76xyssySvLZUbsEPDh9NYJ/ZGW8+NfNW34G/YzG3xHm3aYdAZxxhuw4+h7dfTbwDEYJNQObxxHw06FxcIoSMUkH0Cn5cxRHPnyIbeEE2HmP5GqAdZ2loKqQ0YB/D725AjYOpXy5EYY9JSAoYFH0ZDviaYUzNlGSIwApu/+2CIyXpm9yyRPROgaohQ7DHTkdn9dnZhqrXr5EdMhGLW/Sh359jC2OAVRKbsbwF0FqLpTJXosJhDXQujIMtXZwPKLyE=
  on:
    branch: main
    repo: tosoikea/vodes
    python: 3.8
